apiVersion: v1
kind: Pod
metadata:
  name: insecureubuntu
  namespace: yelb
  labels:
    app: ubuntu
spec:
  # Uncomment and specify a specific node you want to debug
  # nodeName: <insert-node-name-here>
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
      runAsUser: 0
  restartPolicy: Never
  hostIPC: true
  hostNetwork: true
  hostPID: true
